apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: flashstore
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: flashstore