apiVersion: v1
kind: Service

metadata:
  name: payment-service
  namespace: flashstore

  labels:
    app: payment-service
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: flashstore

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3005"

spec:
  type: ClusterIP

  selector:
    app: payment-service

  ports:
    - name: http
      protocol: TCP
      port: 3005
      targetPort: 3005