apiVersion: v1
kind: ServiceAccount

metadata:
  name: prometheus
  namespace: monitoring

  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: flashstore
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: flashstore
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: kubectl

  annotations:
    description: "ServiceAccount for Prometheus"