apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: search-service
  namespace: flashstore

  labels:
    app: search-service
    app.kubernetes.io/name: search-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: flashstore

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: search-service