apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: gateway
  namespace: flashstore

  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: flashstore

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: gateway