apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flashstore

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml

labels:
  - pairs:
      app.kubernetes.io/name: flashstore
      app.kubernetes.io/part-of: flashstore-platform
      managed-by: kustomize