apiVersion: v1
kind: Secret

metadata:
  name: flashstore-secrets
  namespace: flashstore

type: Opaque

stringData:
  MONGO_ROOT_USERNAME: CHANGE_ME
  MONGO_ROOT_PASSWORD: CHANGE_ME

  REDIS_PASSWORD: CHANGE_ME

  JWT_SECRET: CHANGE_ME
  JWT_REFRESH_SECRET: CHANGE_ME

  STRIPE_SECRET_KEY: CHANGE_ME

  EMAIL_USER: CHANGE_ME
  EMAIL_PASS: CHANGE_ME

  KAFKA_USERNAME: CHANGE_ME
  KAFKA_PASSWORD: CHANGE_ME
  KAFKA_CLUSTER_ID: CHANGE_ME

  CLOUDINARY_CLOUD_NAME: CHANGE_ME
  CLOUDINARY_API_KEY: CHANGE_ME
  CLOUDINARY_API_SECRET: CHANGE_ME