apiVersion: v1
kind: Secret

metadata:
  name: flashstore-secrets
  namespace: flashstore

type: Opaque

stringData:

  #####################################
  # MongoDB
  #####################################

  MONGO_ROOT_USERNAME: root
  MONGO_ROOT_PASSWORD: changemeplease

  #####################################
  # Redis
  #####################################

  REDIS_PASSWORD: changemeplease

  #####################################
  # JWT
  #####################################

  JWT_SECRET: your-super-secret-jwt
  JWT_REFRESH_SECRET: your-refresh-token-secret

  #####################################
  # Stripe
  #####################################

  STRIPE_SECRET_KEY: CHANGE_ME

  #####################################
  # Email
  #####################################

  EMAIL_USER: flashmnisi@gmail.com
  EMAIL_PASS: your-app-password

  #####################################
  # Kafka
  #####################################

  KAFKA_USERNAME: admin
  KAFKA_PASSWORD: flashmnisi
  KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  #####################################
  # Cloudinary
  #####################################

  CLOUDINARY_CLOUD_NAME: xxxxx
  CLOUDINARY_API_KEY: xxxxx
  CLOUDINARY_API_SECRET: xxxxx