apiVersion: v1
kind: Service

metadata:
  name: loki
  namespace: monitoring

  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: flashstore
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: flashstore

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: flashstore

  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP