apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - serviceaccount.yml
  - configmap.yml
  - pvc.yml
  - deployment.yml
  - service.yml
  - networkpolicy.yml

labels:
  - pairs:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/instance: flashstore
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/part-of: flashstore