apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: alertmanager-storage
  namespace: monitoring

  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: flashstore
    app.kubernetes.io/version: "0.28.1"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: flashstore
    app.kubernetes.io/managed-by: kubectl

  annotations:
    description: "Persistent storage for Alertmanager"

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  storageClassName: standard