apiVersion: v1
kind: ServiceAccount

metadata:
  name: alertmanager
  namespace: monitoring

  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: flashstore
    app.kubernetes.io/version: "0.28.1"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: flashstore
    app.kubernetes.io/managed-by: kubectl

  annotations:
    description: "ServiceAccount for Alertmanager"