apiVersion: v1
kind: Secret

metadata:
  name: grafana-secret
  namespace: monitoring

  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: flashstore
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: flashstore
    app.kubernetes.io/managed-by: kubectl

  annotations:
    description: "Grafana administrator credentials"

type: Opaque

stringData:
  #####################################
  # Grafana Administrator
  #####################################

  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: changeme

  #####################################
  # Optional SMTP (disabled by default)
  #####################################

  GF_SMTP_USER: ""
  GF_SMTP_PASSWORD: ""