// apps/catalog-service/src/application/use-cases/create-product.usecase.ts

import { ProductEntity } from '../../domain/entities/product.entity';
import { Slug } from '../../domain/value-objects/slug.vo';
import { IProductRepository } from '../../domain/repositories/product.repository';
import { CreateProductDto } from '../dtos/create-product.dto';
import { CatalogProducer } from '../../infrastructure/kafka/producer/catalog.producer';
import logger from '@org/shared-logger';

export class CreateProductUseCase {
  constructor(
    private readonly productRepository: IProductRepository,
    private readonly producer: CatalogProducer
  ) {}

  /**
   * Execute Create Product Use Case with Images
   */
  async execute(
    dto: CreateProductDto, 
    images: string[] = []
  ): Promise<ProductEntity> {
    try {
      // Generate slug from product name
      const slug = Slug.create(dto.name);

      // Create domain entity
      const product = new ProductEntity(
        '', // ID will be generated by MongoDB
        dto.name,
        slug.value,
        dto.description,
        dto.price,
        dto.currency,
        dto.categoryId,
        dto.brand,
        images,                    // ← Images passed here
        dto.tags || [],
        dto.stockQuantity > 0,
        dto.stockQuantity
      );

      // Save to database
      const createdProduct = await this.productRepository.create(product);

      // Publish domain event
      await this.producer.productCreated(createdProduct);

      logger.info('✅ Product created successfully with images', {
        productId: createdProduct.id,
        name: createdProduct.name,
        imageCount: images.length,
      });

      return createdProduct;
    } catch (error: any) {
      logger.error('Failed to create product in use case', {
        error: error.message,
        productName: dto.name,
      });
      throw error;
    }
  }
}