apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: monitoring
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/instance: flashstore
    app.kubernetes.io/part-of: flashstore
spec:
  selector:
    app.kubernetes.io/name: metrics-server
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https