apiVersion: v1
kind: Service

metadata:
  name: inventory-service
  namespace: flashstore

  labels:
    app: inventory-service
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: flashstore

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3008"

spec:
  type: ClusterIP

  selector:
    app: inventory-service

  ports:
    - name: http
      protocol: TCP
      port: 3008
      targetPort: 3008